const predictions = [
  {
    uuid: {
      characterName: "Jax",
      predictedRole: "Rushdown",
      confirmed: "No",
      region: "Runeterra",
      description:
        "Runeterra's greatest weapons master, Jax is the only survivor of the Kohari—champions sworn to the defense of Icathia. But when the Void was unleashed against the Shuriman empire's Ascended Host, Icathia was destroyed, leaving Jax without a home or purpose. He gathered the “last light of Icathia”, a symbol of his hope to one day defeat the Void, and now travels the world, searching for warriors strong enough to face the coming darkness by his side.",
      portrait:
        "https://static.wikia.nocookie.net/leagueoflegends/images/1/1c/06RU008-full.png/revision/latest/scale-to-width-down/1200?cb=20220826181812",
    },
    uuid: {
      characterName: "Jinx",
      predictedRole: "Zoner",
      confirmed: "Yes",
      region: "PNZ",
      description:
        "A manic and impulsive criminal from Zaun, Jinx lives to wreak havoc without care for the consequences. With an arsenal of deadly weapons, she unleashes the loudest blasts and brightest explosions to leave a trail of mayhem and panic in her wake. Jinx despises boredom, and gleefully brings her own chaotic brand of pandemonium wherever she goes.",
      portrait:
        "https://static.wikia.nocookie.net/leagueoflegends/images/9/90/Jinx_Arcane_6_Render.png/revision/latest?cb=20220228021657",
    },
    uuid: {
      characterName: "Darius",
      predictedRole: "Grappler",
      confirmed: "Yes",
      region: "Noxus",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Samira",
      predictedRole: "Rushdown",
      confirmed: "No",
      region: "Noxus",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Yasuo",
      predictedRole: "Shoto",
      confirmed: "No",
      region: "Ionia",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Illaoi",
      predictedRole: "Grappler",
      confirmed: "Yes",
      region: "Bilgewater",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Bard",
      predictedRole: "Joke Character",
      confirmed: "No",
      region: "Runeterra",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Katarina",
      predictedRole: "Rushdown",
      confirmed: "Yes",
      region: "Noxus",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Gangplank",
      predictedRole: "Zoner",
      confirmed: "No",
      region: "Bilgewater",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Udyr",
      predictedRole: "Stance-Swapper",
      confirmed: "No",
      region: "Freljord",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Neeko",
      predictedRole: "Mimic",
      confirmed: "No",
      region: "Ixtal",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Azir",
      predictedRole: "Zoner",
      confirmed: "No",
      region: "Shurima",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Gnar",
      predictedRole: "Stance-Swapper",
      confirmed: "No",
      region: "Bandle",
      description: "",
      portrait: "",
    },
    uuid: {
      characterName: "Fiora",
      predictedRole: "Rushdown",
      confirmed: "THANK GOD NO",
      region: "Demacia",
      description: "",
      portrait: "",
    },
  },
];
export { predictions };
